name: CD
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'


jobs:
  deploy-app:
    steps:
     -  name : deploy alec app
     -  run : |
     curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_HYsKjf0N2J03sCou0rcBYTtlzcD7/9PxEvGBy1J?buildCache=false